Tournament tscheck
LDS-Gamers-Studios/icarus5.5 pull request #67
Opened 2024-04-19 20:41 UTC by LDSGOhGo

passes tscheck, and is tested.

2024-04-20 02:07 UTC, BobbyTheCatfish commented
Made a few changes to simplify stuff. I've tested it but I want you to test it as well and give me your thoughts

2024-04-20 13:46 UTC, BobbyTheCatfish approved these changes

2024-04-20 21:17 UTC, LDSGOhGo commented
Tested, works great just had to fix the replies for the participant command to be edits of a deferred reply.

2024-04-21 03:40 UTC, BobbyTheCatfish requested changes
Final few changes, I can apply them

2024-04-21 03:40 UTC, BobbyTheCatfish commented on modules/tournament.js
>    if (displayTourneys.length == 0) return int.editReply({ content: "Looks like there aren't any tourneys scheduled right now." });
```suggestion
  if (displayTourneys.length == 0) return int.editReply("Looks like there aren't any tourneys scheduled right now.");
```

2024-04-21 03:40 UTC, BobbyTheCatfish commented on modules/tournament.js
> +    return int.editReply({ content: `Removed ${succeeded}/${members.size} people from the ${role} role` });
```suggestion
    return int.editReply(`Removed ${succeeded}/${members.size} people from the ${role} role`);
```

2024-04-21 03:40 UTC, BobbyTheCatfish commented on modules/tournament.js
> +      return int.editReply({ content });
```suggestion
      return int.editReply(content);
```

2024-04-21 03:40 UTC, BobbyTheCatfish commented on modules/tournament.js
> +      return int.editReply({ content: `${user} doesn't have the ${role} role` });
```suggestion
      return int.editReply(`${user} doesn't have the ${role} role`);
```

2024-04-21 03:40 UTC, BobbyTheCatfish commented on modules/tournament.js
> +    return int.editReply({ content: `${user} already has the ${role} role` });
```suggestion
    return int.editReply(`${user} already has the ${role} role`);
```

2024-04-21 03:41 UTC, BobbyTheCatfish approved these changes

2024-04-21 03:41 UTC, merged